package green.chencheng.bwie.com.fjd_activity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import chencheng.bwie.com.fjd_activity.green.SousBeanDao;
import chencheng.bwie.com.fjd_activity.homepage.bean.SousBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sousBeanDaoConfig;

    private final SousBeanDao sousBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sousBeanDaoConfig = daoConfigMap.get(SousBeanDao.class).clone();
        sousBeanDaoConfig.initIdentityScope(type);

        sousBeanDao = new SousBeanDao(sousBeanDaoConfig, this);

        registerDao(SousBean.class, sousBeanDao);
    }
    
    public void clear() {
        sousBeanDaoConfig.clearIdentityScope();
    }

    public SousBeanDao getSousBeanDao() {
        return sousBeanDao;
    }

}
